import type { Metadata } from "next";
import "./globals.css";
import Provider from "./provider";
import Navbar from "@nextCode/components/custom/c_Navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      >
        <Provider>
          <Navbar />
        {children}
        </Provider>
      </body>
    </html>
  );
}
